version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: income-scraper-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: majors_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/01-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data:
